### ISSUE TITLE
mod/rmod missing

### ISSUE THREAD

**Issue by leahneukirchen** [andrewchambers/janet-bigcalc#11]
This breaks the default definitions of even? and odd?.

Should work with bf_divrem BF_DIVREM_EUCLIDIAN.

**Comment by leahneukirchen** [comment]
Hm, but even?/odd? also don't use compare=...

**Comment by MikeBeller** [comment]
Hey Leah -- I don't think they are missing.  I did not have them in the test suite -- that was an oversight which I am correcting.  See the below tests, which work just fine in the current version.

As to even? odd? -- they will not work for big/ints -- unless @bakpakin would want to change those to use polymorphic compare.  But not sure that's really necessary/desirable.  I can put some text in the readme to remind people that the only numeric functions not in the janet/big library that work with big/ints are the +,-,*,/,%, &,|,^ operators (forward/reverse), and polymorphic (but not basic) comparison.

```
(assert (= (big/int 708) (% (big/int "23456453431782954574257") 4923)))
(assert (= (big/int 1427) (% 2345678992 (big/int 4711))))
```

Let me know if I misunderstood the issue.

**Comment by MikeBeller** [comment]
Decided to expose divmod (returns a tuple of quotient, remainder) also.  However I don't think fixing even? odd? is in the scope of this project. (It's a core thing.)  See PR.

**Comment by leahneukirchen** [comment]
Looks good, but providing % and not mod is inconsistent.

**Comment by MikeBeller** [comment]
Ah.  Now i understand what you are saying.  Yes that's easy to add.  I will do that and update the PR.

**Comment by leahneukirchen** [comment]
Note that it works differently for negative numbers than %!

**Comment by MikeBeller** [comment]
Oops.  Thanks.

**Comment by MikeBeller** [comment]
Ok new updates on the PR separate % from mod and add divrem/divmod.  BTW: even? / odd? *do* work properly.  They were updated to be based on polymorphic comparison, so they just work. (as do zero? one? etc...).  Thanks for your input @leahneukirchen
