### ISSUE TITLE
Expose bf_pow

### ISSUE THREAD

**Issue by leahneukirchen** [andrewchambers/janet-bigcalc#12]
There is no easy way to compute a power currently without iterating yourself, but libbf has the convenient bf_pow.

**Comment by MikeBeller** [comment]
Thanks Leah -- yes and there are a lot of transcendentals in libbf.  I've been waiting to build up the motivation to add this.  Maybe I will do a PR adding this and fixing some of the other items you noticed.

**Comment by MikeBeller** [comment]
Errr... not the transcendentals.  But isqrt for example.  Potentially.

**Comment by MikeBeller** [comment]
Issued a PR today for this.
