### ISSUE TITLE
Insufficient validation for big/int

### ISSUE THREAD

**Issue by leahneukirchen** [andrewchambers/janet-bigcalc#14]
```
> (big/int "100a")
<big/int 100>
> (big/int "zz")
<big/int NaN>
> (big/int "100_000")
<big/int 100>
```

I think it should behave more like scan-number, and return nil in the first two cases, and if it could parse the third case that would be even better.

**Comment by MikeBeller** [comment]
Thanks @leahneukirchen for pointing this out.   I just issued pr #15 to address all 3 items.
