### ISSUE TITLE
Too low precision for stringifying long numbers

### ISSUE THREAD

**Issue by leahneukirchen** [andrewchambers/janet-bigcalc#8]
If a number has around 100 digits, the string function renders it using e-notation:

```
repl:8:> (string (* (big/int 1) ;(range 1 72)))
"850478588567862317521167644239926010288584608120796235886430763388588680378079017697280000000000000000"
repl:9:> (string (* (big/int 1) ;(range 1 73)))
"6.123445837688608686152407038527467274077809178469732898382301496397838498722168927420416e103"
```

The system computes with the exact number, of course. But there is no way to get them out.

I think the computation of `prec` in `big_digits` is too low. Adding a `* 2` there also allows rendering a 300k long digit,
but perhaps there is a better bound.

I'd also recommend adding a unit test that computes a big number and checks no "e" appears in `(string n)`.

**Comment by MikeBeller** [comment]
Thanks Leah.   I do remember there being something hacky about my code to get libbf (the library by Fabrice Bellard upon which janet-big is now based) to print all the digits.  Like I guessed at some parameter.  And clearly you are right some tests are in order.  I will look into it and revert with a PR.

**Comment by MikeBeller** [comment]
Ok -- that was interesting.  I dug in to Bellard's "quickjs" code and figured out how he handles precision in his javascript interpreter (which supports both BigInts and BigFloats).  I copied his approach.  Which is what i should have done in the first place.

**Comment by leahneukirchen** [comment]
Looks good.

**Comment by andrewchambers** [comment]
Thanks so much!

**Comment by MikeBeller** [comment]
My pleasure. Thanks to @leahneukirchen for pointing it out.
